version: '2'

services:
    web:
        build: .
        image: deep_image
        ports:
            - 5050:5050
        env_file: .env
        depends_on:
            - db
        volumes:
            - .:/opt/deep-pictionary
        # command: tail -f /dev/null
        # command: python manage.py runserver 0.0.0.0:5050
        command: gunicorn --bind 0.0.0.0:$PORT deep-pictionary.wsgi
    db:
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - deep_db_vol:/var/lib/postgresql/data

volumes:
    deep_db_vol:
