# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitmap', models.CharField(max_length=900)),
                ('category', models.CharField(max_length=20)),
                ('draw_date', models.DateTimeField(verbose_name='date of drawing')),
            ],
        ),
    ]
